<a href="https://colab.research.google.com/github/MathewS424/PyTorch-Tutorial/blob/main/02_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_list = [[1, 2, 3]]
my_list

[[1, 2, 3]]

In [3]:
np1 = np.random.rand(3, 4)
np1

array([[0.11815363, 0.37201638, 0.97357544, 0.26415725],
       [0.29174346, 0.84214303, 0.73850436, 0.59533981],
       [0.32708227, 0.96305272, 0.95703219, 0.84614213]])

In [4]:
np1.dtype

dtype('float64')

In [5]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 1.8413,  0.3929, -1.2807,  0.8641],
        [ 0.6080, -0.7437,  1.0197, -0.4588],
        [-0.6753,  1.9816,  0.9719,  0.5741]])

In [6]:
tensor_3d = torch.zeros(3, 4)
tensor_3d

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
# Create tensor from numpy
tensor_from_numpy = torch.tensor(np1)
print(tensor_from_numpy)
tensor_from_numpy2 = torch.from_numpy(np1)
tensor_from_numpy2

tensor([[0.1182, 0.3720, 0.9736, 0.2642],
        [0.2917, 0.8421, 0.7385, 0.5953],
        [0.3271, 0.9631, 0.9570, 0.8461]], dtype=torch.float64)


tensor([[0.1182, 0.3720, 0.9736, 0.2642],
        [0.2917, 0.8421, 0.7385, 0.5953],
        [0.3271, 0.9631, 0.9570, 0.8461]], dtype=torch.float64)