<a href="https://colab.research.google.com/github/MathewS424/PyTorch-Tutorial/blob/main/03_Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Reshape and view
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
my_torch = my_torch.reshape(2, 6)
my_torch

RuntimeError: shape '[2, 6]' is invalid for input of size 10

In [5]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Reshape if we dont know the number of items using -1
my_torch = my_torch2.reshape(2, -1)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
# Reshape if we dont know the number of items using -1
my_torch = my_torch2.reshape(2, -1)
my_torch

RuntimeError: shape '[2, -1]' is invalid for input of size 15

In [10]:
# Reshape if we dont know the number of items using -1
my_torch = my_torch2.reshape(3, -1)
my_torch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [11]:
# Reshape if we dont know the number of items using -1
my_torch = my_torch2.reshape(-1, 5)
my_torch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [13]:
# View
my_torch3 = torch.arange(10)
my_torch = my_torch3.view(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Another difference is that reshape() can operate on both contiguous and non-contiguous tensor while view() can only operate on contiguous tensor. Also see here about the meaning of contiguous.

In [19]:
# with reshape, view they will update
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch5 = my_torch4.reshape(2, 5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
my_torch4[1] = 4141
my_torch4

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [22]:
my_torch5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [23]:
# Slices
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Gab a specific item
my_torch6[7]

tensor(7)

In [27]:
# Grab a slice
my_torch8 = my_torch6.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [29]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [31]:
# rETURN COLUMN
my_torch8[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])