<a href="https://colab.research.google.com/github/MathewS424/PyTorch-Tutorial/blob/main/04_Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [22]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
# Substract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [8]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [9]:
# MultiPly
tensor_b * tensor_a

tensor([ 5, 12, 21, 32])

In [10]:
# Mul Function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
# Div Function
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# Modulus or reminder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [15]:
# Reminder Function
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [16]:
# Exponents /Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [23]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [24]:
tensor_a

tensor([1, 2, 3, 4])

In [25]:
tensor_a = tensor_a + tensor_b
tensor_a

tensor([ 6,  8, 10, 12])

In [29]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [30]:
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])

In [31]:
torch.add_(tensor_a, tensor_b)

AttributeError: module 'torch' has no attribute 'add_'